export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
export const ADD_PRODUCTS_LS = ' ADD_PRODUCTS_LS';
export const EDIT_PRODUCTS_LS = 'EDIT_PRODUCTS_LS';
export const DEL_PRODUCTS_LS = 'DEL_PRODUCTS_LS';