export const navData = {
    local_warehouse: {
        "EU Warehouse": ["EU Deals"],
        "DE Warehouse": ["DE Deals"],
        "PL Warehouse": ["PL Deals"],
        "ES Warehouse": ["ES Deals"],
        "IT Warehouse": ["IT Deals"],
        "CZ Warehouse": [],
        "EU-3 Warehouse": [],
        "UK Warehouse": ["UK Deals"],
        "USA Warehouse": ["USA Deals"],
        "image": "https://img.gkbcdn.com/s3/cim/category-1301-6ETJOmbg.png",
    },
    sports_outdoors: {
        "E-Bikes, Scooters &amp; Wheels": ["Bikes", "Electric Scooters", "Electric Skateboards","Accessories"],
        "Exercise": ["Fitness &amp; Body Building", "Water Sports", "Yoga &amp; Pilates", "Weightlifting", "Cardio","Indoor Games"],
        "Cycling": ["Bike Computers", "Bike Bags", "Bike Tools", "Bike Lights", "Cycling Apparels","Other Accessories"],
        "Camping &amp; Hiking": ["Luggage &amp; Bags", "Tent &amp; Hammock", "Travel Supplies","Knives &amp; Multi Tools"],
        "Outdoor Generators":[],
        "Flashlight &amp; Torch":[],
        "Outdoor Sports Cameras":[],
        "Hunting &amp; Shooting":[],
        "Outdoor Recreation":[],
        "Outdoor Apparels":[],
        "Athletics":[],
        "image":"https://img.gkbcdn.com/s3/cim/category-1241-6g70jAZ2.png",
    },
    smart_home_garden: {
        "Smart Home &amp; Garden": ["Smart Home", "Robot Vacuum Cleaners", "Cordless Vacuum Cleaners", "Fitness", "Smart Sockets &amp; Switches", "Smart Lights", "Xiaomi Smart Gadgets", "Air Purifier","Others"],
        "Kitchen &amp; Dining": ["Kitchen Appliances", "Cookware", "Bakeware", "Tableware", "Barware", "Kitchen Tools &amp; Gadgets","Others"],
        "Household Appliances":[],
        "Furniture": ["Outdoor Furniture", "Tables", "Chairs", "Beds &amp; Accessories", "Cabinets &amp; Storage", "Shelving", "Entertainment Centres &amp; TV Stands","Furniture Sets"],
        "Patio, Lawn &amp; Garden": ["Pots &amp; Planters", "Watering &amp; Irrigation", "Mowers &amp; Outdoor Power Tools","Other Garden Supplies"],
        "Health &amp; Beauty": ["Personal Care", "Health Care","Massage &amp; Relaxation"],
        "Home Decors": ["Rugs", "Door Mats", "Window Treatments", "Mirrors","Artificial Flora"],
        "Household Supplies": ["Storage &amp; Organization","Household Cleaning Supplies"],
        "Lighting":[],
        "Tools &amp; Home Improvement":[],
        "Office Supplies":[],
        "Pet Supplies":[],
        "Bathroom Supplies": [],
        "image": "https://img.gkbcdn.com/s3/cim/category-174-6g72l4ct.png",
    },
    consumer_electronics: {
        "3D Printers &amp; Accessories": ["FDM 3D Printers", "SLA 3D Printers","3D Printer Accessories"],
        "Laser Engravers &amp; Cutters": ["Desktop Laser Engravers"],
        "Bluetooth Speakers": ["Wireless &amp; Bluetooth Speakers", "Outdoor Speakers","Accessories"],
        "Laser Engravers &amp; Cutters":[],
        "Headphones &amp; Earphones": ["Earbud Headphones", "On-ear &amp; Over-ear Headphones", "Sports &amp; Fitness Headphones","Headphone Accessories"],
        "Projectors":[],
        "Video Games Accessories": ["Handheld Game Consoles", "PC Gaming Controllers", "Retro Gaming", "PlayStation", "Nintendo","Other Game Accessories"],
        "Professional Instruments &amp; Tools": ["Measurement &amp; Analysis Instruments","Maintenance &amp; Repair Tools"],
        "Memory Card":[],
        "Cameras &amp; Optics": [],
        "Power Banks &amp; Chargers": [],
        "Audio &amp; Video Accessories": [],
        "image":"https://img.gkbcdn.com/s3/cim/category-177-6PuYwF6n.png",
    },
    tv_boxex_mini_pcs: {
        "Windows Mini PCs": [],
        "Android TV Boxes": [],
        "Android TV Sticks": [],
        "Barebone Mini PC": [],
        "MINI PC Accessories &amp; Gadgets": [],
        "Bundle &amp; Discount Zone": [],
        "image": "https://img.gkbcdn.com/s3/cim/category-505-6gdY9WM0.png",
    },
    computer_tablet_accessories: {
        "Laptops": ["Ultrabooks","Gaming Laptops"],
        "Tablets": ["Android Tablets","Windows Tablets"],
        "Laptop Accessories": [],
        "Computer Components": ["DIY PC", "SSD &amp; HDD &amp; Enclosures", "PC Power Supplies", "Fan &amp; Cooling","Monitors"],
        "Graphic Tablets": [],
        "USB Gadgets": [],
        "Keyboard &amp; Mouse": ["Wireless Keyboards", "Wired Keyboards", "Wireless Mouse", "Wired Mouse","Keyboard and Mice Kit"],
        "Tronsmart Chargers": ["Tronsmart Wall Chargers","Tronsmart Cables"],
        "Networking": [],
        "Other Accessories": ["Webcams", "Adapters","Cables"],
        "image": "https://img.gkbcdn.com/s3/cim/category-971-6gdYDFyQ.png",
    },
    toy_hobbies: {
        "RC Drones": ["RC Quadcopters", "FPV Racing Drone", "RC Airplanes","RC Helicopters"],
        "RC Vehicles": ["RC Cars","RC Boats"],
        "FPV System": [],
        "RC Parts": ["RC Boat Parts", "RC Car Parts", "RC Quadcopter Parts","Multi Rotor Parts"],
        "RC Robot": [],
        "Building Sets &amp; Blocks": [],
        "Musical Instruments &amp; Hobbies": ["Strings", "Drums &amp; Percussion", "Other Musical Instruments","Other Hobbies"],
        "Outdoor Play Equipment": ["Swing Sets &amp; Playsets", "Trampolines","Kids&#39; Playhouses"],
        "Toys": ["Dolls, Playsets &amp; Toy Figures", "Puzzle Toys","Holidays &amp; Party"],
        "image": "https://img.gkbcdn.com/s3/cim/category-742-6ETJw428.png",
    },
    phone_accessories: {
        "Cell Phones": ["5G Smartphones","4G Smartphones"],
        "Phone Accessories": ["Screen Protectors","Cases &amp; Covers"],
        "Apple Accessories": [],
        "image": "	https://img.gkbcdn.com/s3/cim/category-178-6gdYEFpk.png",
    },
    automobile_motorcycle: {
        "Car DVRs": [],
        "Car Alarm &amp; Security": [],
        "Car Lights": ["Car LED Bulbs","HID Xenon Lights"],
        "Car Chargers": ["Car Decorations"],
        "Car Repair &amp; Maintenance": [],
        "Car Parts &amp; Gadgets": [],
        "image": "https://img.gkbcdn.com/s3/cim/category-439-6ETK2wXA.png",
    },
    wearable_devices: {
        "Smart Watches": [],
        "Smart Bracelets": [],
        "Wearables Accessories": [],
        "image": "https://img.gkbcdn.com/s3/cim/category-1549-6PNrOAEo.png",
    },
    security_system: {
        "Security Cameras": ["IP Cameras"],
        "Surveillance DVR Systems": ["NVR Kits"],
        "Access Control Systems": ["Access Controller &amp; Key","Video Door Phones"],
        "Security System Accessories ": [],
        "image": "https://img.gkbcdn.com/s3/cim/category-215-6HdYHAm8.png",
    },
    fashion: {
        "Watches": ["Pocket Watches","Women&#39;s Watches"],
        "Jewelry": ["Rings", "Earrings", "Necklaces &amp; Pendants","Others"],
        "Clothing": ["Uniforms", "Suits", "Shirts &amp; Tops","Others"],
        "Bags &amp; Shoes": ["Shoes","Handbags, Wallets &amp; Cases"],
        "image": "https://img.gkbcdn.com/s3/cim/category-2060-6ETN75P3.png",
    },
}